import { registerFeedHandlers } from './feed-handlers';
import { registerArticleHandlers } from './article-handlers';
import { registerHighlightHandlers } from './highlight-handlers';
import { registerTagHandlers } from './tag-handlers';
import { registerExportHandlers } from './export-handlers';
import { registerBookHandlers } from './book-handlers';
import { registerHighlightTagHandlers } from './highlight-tag-handlers';
import { registerTranscriptHandlers } from './transcript-handlers';
import { registerPodcastHandlers } from './podcast-handlers';
import { registerSettingsHandlers } from './settings-handlers';
import { registerDownloadHandlers } from './download-handlers';
import { registerDiscoverHandlers } from './discover-handlers';
import { registerNewsletterHandlers } from './newsletter-handlers';
import { registerShareCardHandlers } from './share-card-handlers';
import { registerAIHandlers } from './ai-handlers';
import { registerAsrHandlers } from './asr-handlers';
import { registerAppTaskHandlers } from './app-task-handlers';
import { registerNotificationHandlers } from './notification-handlers';
import { registerExternalHandlers } from './external-handlers';
import { registerSyncHandlers } from './sync-handlers';
import { registerWechatHandlers } from './wechat-handlers';
import { registerRAGHandlers } from './rag-handlers';
import { registerKGHandlers } from './kg-handlers';
import { registerFeedRelevanceHandlers } from './feed-relevance-handlers';
import { registerWritingAssistHandlers } from './writing-assist-handlers';
import { registerBackfillHandlers } from './backfill-handlers';
import { registerEmbeddingConfigHandlers } from './embedding-config-handlers';

export function registerAllIpcHandlers() {
  registerFeedHandlers();
  registerArticleHandlers();
  registerHighlightHandlers();
  registerTagHandlers();
  registerExportHandlers();
  registerBookHandlers();
  registerHighlightTagHandlers();
  registerTranscriptHandlers();
  registerPodcastHandlers();
  registerSettingsHandlers();
  registerDownloadHandlers();
  registerDiscoverHandlers();
  registerNewsletterHandlers();
  registerShareCardHandlers();
  registerAIHandlers();
  registerAsrHandlers();
  registerAppTaskHandlers();
  registerNotificationHandlers();
  registerExternalHandlers();
  registerSyncHandlers();
  registerWechatHandlers();
  registerRAGHandlers();
  registerKGHandlers();
  registerFeedRelevanceHandlers();
  registerWritingAssistHandlers();
  registerBackfillHandlers();
  registerEmbeddingConfigHandlers();
}
